In [1]:
import pandas as pd
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
data = pd.read_csv('/content/drive/MyDrive/NLP project/Data/data_annotated.csv')
data

,text,category,bad words,cyberbullying
0,قاتلك هاذاك الإنسان ال gris 😭,appearance bullying,NaN,cyberbullying
1,Never saw his skin color lol,appearance bullying,NaN,cyberbullying
2,السيد لي ماشي grey,appearance bullying,NaN,cyberbullying
3,Say dok ghi syed li 3andou 1000 3adala,not offensive,NaN,not cyberbullying
4,😂,not offensive,NaN,not cyberbullying
...,...,...,...,...
60404,باين بلي فيلم جديد,not offensive,NaN,not cyberbullying
60405,My ballsssssss,cursing,NaN,NaN
60406,حكمتني لدياري منها,intimidating speech,NaN,cyberbullying
60407,@tewsst._.nono ',not offensive,NaN,NaN
60408,😂😂😂😂😂,not offensive,NaN,NaN

In [3]:
data.dropna(subset=['text'], inplace = True)
data

,text,category,bad words,cyberbullying
0,قاتلك هاذاك الإنسان ال gris 😭,appearance bullying,NaN,cyberbullying
1,Never saw his skin color lol,appearance bullying,NaN,cyberbullying
2,السيد لي ماشي grey,appearance bullying,NaN,cyberbullying
3,Say dok ghi syed li 3andou 1000 3adala,not offensive,NaN,not cyberbullying
4,😂,not offensive,NaN,not cyberbullying
...,...,...,...,...
60404,باين بلي فيلم جديد,not offensive,NaN,not cyberbullying
60405,My ballsssssss,cursing,NaN,NaN
60406,حكمتني لدياري منها,intimidating speech,NaN,cyberbullying
60407,@tewsst._.nono ',not offensive,NaN,NaN
60408,😂😂😂😂😂,not offensive,NaN,NaN

In [4]:
data.category.unique()

array(['appearance bullying', 'not offensive', 'judgement', 'sarcasm',
       nan, 'drugs', 'mockery', 'intimidating speech', 'exclusion',
       'cursing', 'harassment', 'rumor spreading', 'racism', 'trolling',
       'misogyny', 'violence', 'religious extremism'], dtype=object)

In [5]:
data['category'] = data['category'].apply(
    lambda x: "not cyberbullying" if x == "not offensive"
    else "cyberbullying" if x in [
        'appearance bullying', 'judgement', 'sarcasm', 'drugs',
        'mockery', 'intimidating speech', 'exclusion', 'cursing',
        'harassment', 'rumor spreading', 'racism', 'trolling',
        'misogyny', 'violence', 'religious extremism'
    ] else np.nan
)

data

,text,category,bad words,cyberbullying
0,قاتلك هاذاك الإنسان ال gris 😭,cyberbullying,NaN,cyberbullying
1,Never saw his skin color lol,cyberbullying,NaN,cyberbullying
2,السيد لي ماشي grey,cyberbullying,NaN,cyberbullying
3,Say dok ghi syed li 3andou 1000 3adala,not cyberbullying,NaN,not cyberbullying
4,😂,not cyberbullying,NaN,not cyberbullying
...,...,...,...,...
60404,باين بلي فيلم جديد,not cyberbullying,NaN,not cyberbullying
60405,My ballsssssss,cyberbullying,NaN,NaN
60406,حكمتني لدياري منها,cyberbullying,NaN,cyberbullying
60407,@tewsst._.nono ',not cyberbullying,NaN,NaN
60408,😂😂😂😂😂,not cyberbullying,NaN,NaN

In [6]:
data.category.unique()

array(['cyberbullying', 'not cyberbullying', nan], dtype=object)

In [7]:
data.cyberbullying.unique()

array(['cyberbullying', 'not cyberbullying', 'context based', nan],
      dtype=object)

In [8]:
data.dropna(subset = ['cyberbullying', 'category'], how='all', inplace = True)
data

,text,category,bad words,cyberbullying
0,قاتلك هاذاك الإنسان ال gris 😭,cyberbullying,NaN,cyberbullying
1,Never saw his skin color lol,cyberbullying,NaN,cyberbullying
2,السيد لي ماشي grey,cyberbullying,NaN,cyberbullying
3,Say dok ghi syed li 3andou 1000 3adala,not cyberbullying,NaN,not cyberbullying
4,😂,not cyberbullying,NaN,not cyberbullying
...,...,...,...,...
60404,باين بلي فيلم جديد,not cyberbullying,NaN,not cyberbullying
60405,My ballsssssss,cyberbullying,NaN,NaN
60406,حكمتني لدياري منها,cyberbullying,NaN,cyberbullying
60407,@tewsst._.nono ',not cyberbullying,NaN,NaN
60408,😂😂😂😂😂,not cyberbullying,NaN,NaN

In [9]:
data["combined"] = data["category"].combine_first(data["cyberbullying"])
data

,text,category,bad words,cyberbullying,combined
0,قاتلك هاذاك الإنسان ال gris 😭,cyberbullying,NaN,cyberbullying,cyberbullying
1,Never saw his skin color lol,cyberbullying,NaN,cyberbullying,cyberbullying
2,السيد لي ماشي grey,cyberbullying,NaN,cyberbullying,cyberbullying
3,Say dok ghi syed li 3andou 1000 3adala,not cyberbullying,NaN,not cyberbullying,not cyberbullying
4,😂,not cyberbullying,NaN,not cyberbullying,not cyberbullying
...,...,...,...,...,...
60404,باين بلي فيلم جديد,not cyberbullying,NaN,not cyberbullying,not cyberbullying
60405,My ballsssssss,cyberbullying,NaN,NaN,cyberbullying
60406,حكمتني لدياري منها,cyberbullying,NaN,cyberbullying,cyberbullying
60407,@tewsst._.nono ',not cyberbullying,NaN,NaN,not cyberbullying
60408,😂😂😂😂😂,not cyberbullying,NaN,NaN,not cyberbullying

In [10]:
data.drop(columns = ['category', 'cyberbullying', 'bad words'], inplace =True)
data

                                         text           combined
0               قاتلك هاذاك الإنسان ال gris 😭      cyberbullying
1                Never saw his skin color lol      cyberbullying
2                          السيد لي ماشي grey      cyberbullying
3      Say dok ghi syed li 3andou 1000 3adala  not cyberbullying
4                                           😂  not cyberbullying
...                                       ...                ...
60404                      باين بلي فيلم جديد  not cyberbullying
60405                          My ballsssssss      cyberbullying
60406                      حكمتني لدياري منها      cyberbullying
60407                        @tewsst._.nono '  not cyberbullying
60408                                   😂😂😂😂😂  not cyberbullying

[30781 rows x 2 columns]

In [11]:
data.rename(columns ={'combined' : 'label'}, inplace = True)
data

                                         text              label
0               قاتلك هاذاك الإنسان ال gris 😭      cyberbullying
1                Never saw his skin color lol      cyberbullying
2                          السيد لي ماشي grey      cyberbullying
3      Say dok ghi syed li 3andou 1000 3adala  not cyberbullying
4                                           😂  not cyberbullying
...                                       ...                ...
60404                      باين بلي فيلم جديد  not cyberbullying
60405                          My ballsssssss      cyberbullying
60406                      حكمتني لدياري منها      cyberbullying
60407                        @tewsst._.nono '  not cyberbullying
60408                                   😂😂😂😂😂  not cyberbullying

[30781 rows x 2 columns]

In [12]:
data.describe()

         text              label
count   30781              30781
unique  27906                  3
top      😂😂😂😂  not cyberbullying
freq       53              24284

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30781 entries, 0 to 60408
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    30781 non-null  object
 1   label   30781 non-null  object
dtypes: object(2)
memory usage: 721.4+ KB

In [14]:
import plotly.express as px


label_counts = data['label'].value_counts().reset_index()
label_counts.columns = ['Label', 'Count']


fig = px.bar(
    label_counts,
    x='Label',
    y='Count',
    color='Label',
    title='Distribution of Labels',
    labels={'Category': 'Category', 'Count': 'Count'},
)

fig.update_layout(
    xaxis_title='Category',
    yaxis_title='Count',
    xaxis_tickangle=45,
    font=dict(size=12)
)


fig.show()

## Adding the dictionary data to the data

In [15]:
dic = pd.read_csv('/content/drive/MyDrive/NLP project/Data/final_dict - final_dict.csv')
dic

      Unnamed: 0    bad_word   severity  Unnamed: 3         latin
0            0.0       مهبول   9.000000         NaN       mahboul
1            1.0        جايح   8.445312         NaN         jayeh
2            2.0         زبل   7.250000         NaN          zbel
3            3.0        خرية   5.500000         NaN        kharya
4            4.0  الله يلعنك  10.000000         NaN  allah yl3nek
...          ...         ...        ...         ...           ...
1342       260.0       فرعون        NaN         NaN       fer3oun
1343       260.0      بوجبهة        NaN         NaN      boujebha
1344       260.0       سلقوط        NaN         NaN        sel9ot
1345       260.0        لحكل        NaN         NaN        lek7al
1346       260.0       بوكرش        NaN         NaN      boukerch

[1347 rows x 5 columns]

In [16]:
dic.drop(columns = ['Unnamed: 0', 'severity', 'Unnamed: 3'], inplace = True)
dic

        bad_word         latin
0          مهبول       mahboul
1           جايح         jayeh
2            زبل          zbel
3           خرية        kharya
4     الله يلعنك  allah yl3nek
...          ...           ...
1342       فرعون       fer3oun
1343      بوجبهة      boujebha
1344       سلقوط        sel9ot
1345        لحكل        lek7al
1346       بوكرش      boukerch

[1347 rows x 2 columns]

In [17]:
text1 = dic['bad_word']
text2 = dic['latin']

In [18]:
text = pd.concat([text1,text2], axis = 0).reset_index(drop=True)
text

0            مهبول
1             جايح
2              زبل
3             خرية
4       الله يلعنك
           ...
2689       fer3oun
2690      boujebha
2691        sel9ot
2692        lek7al
2693      boukerch
Length: 2694, dtype: object

In [19]:
text = text.to_frame(name='text')
text

            text
0          مهبول
1           جايح
2            زبل
3           خرية
4     الله يلعنك
...          ...
2689     fer3oun
2690    boujebha
2691      sel9ot
2692      lek7al
2693    boukerch

[2694 rows x 1 columns]

In [20]:
text.dropna(subset = ['text'], inplace = True)
text

            text
0          مهبول
1           جايح
2            زبل
3           خرية
4     الله يلعنك
...          ...
2689     fer3oun
2690    boujebha
2691      sel9ot
2692      lek7al
2693    boukerch

[2220 rows x 1 columns]

In [21]:
text['label'] = 'cyberbullying'
text

            text          label
0          مهبول  cyberbullying
1           جايح  cyberbullying
2            زبل  cyberbullying
3           خرية  cyberbullying
4     الله يلعنك  cyberbullying
...          ...            ...
2689     fer3oun  cyberbullying
2690    boujebha  cyberbullying
2691      sel9ot  cyberbullying
2692      lek7al  cyberbullying
2693    boukerch  cyberbullying

[2220 rows x 2 columns]

In [22]:
the_data = pd.concat([data, text], axis = 0).reset_index(drop = True)
the_data

                                         text              label
0               قاتلك هاذاك الإنسان ال gris 😭      cyberbullying
1                Never saw his skin color lol      cyberbullying
2                          السيد لي ماشي grey      cyberbullying
3      Say dok ghi syed li 3andou 1000 3adala  not cyberbullying
4                                           😂  not cyberbullying
...                                       ...                ...
32996                                 fer3oun      cyberbullying
32997                                boujebha      cyberbullying
32998                                  sel9ot      cyberbullying
32999                                  lek7al      cyberbullying
33000                                boukerch      cyberbullying

[33001 rows x 2 columns]

In [23]:
import plotly.express as px


label_counts = the_data['label'].value_counts().reset_index()
label_counts.columns = ['Label', 'Count']


fig = px.bar(
    label_counts,
    x='Label',
    y='Count',
    color='Label',
    title='Distribution of Labels',
    labels={'Category': 'Category', 'Count': 'Count'},
)

fig.update_layout(
    xaxis_title='Category',
    yaxis_title='Count',
    xaxis_tickangle=45,
    font=dict(size=12)
)


fig.show()

## Data generation: for data augmentation: rewriting the words of the dictionary in different ways

In [25]:
!pip install langdetect

Requirement already satisfied: langdetect in /usr/local/lib/python3.10/dist-packages (1.0.9)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from langdetect) (1.17.0)

In [26]:
import pandas as pd
from langdetect import detect

# Function to generate new variations by swapping characters
def generate_variations(word):
    variations = [word]  # Start with the original word

    # Detect the language of the word
    try:
        lang = detect(word)  # Detects language: 'ar' for Arabic, 'en' for English, etc.
    except:
        lang = 'unknown'

    # Arabic-specific swaps
    if lang == 'ar':
        swaps = {
          'ا': 'آ',  # Alef to Alif with a long sound
          'و': 'ؤ',  # Waw to Waw with Hamza
          'ع': 'غ',  # Ayn to Ghayn
          'ي': 'ئ',  # Yeh to Yeh with Hamza
          'ا': 'ى',  # Alif to Alef Maksura
          'و': 'ى',  # Waw to Alef Maksura (in some dialects)
          'ي': 'ى',  # Yeh to Alef Maksura (in some dialects)
          'ه': 'ة',  # Ha to Taa Marbuta
          'ق': 'ك',  # Qaf to Kaf (in dialects)
          'غ': 'خ',  # Ghayn to Khaa (in dialects)
          'ص': 'ض',  # Sinn to Sad (in dialects)
          'د': 'ز',  # Daal to Zay (in some informal cases)
          'ش': 'س',  # Shin to Seen (in some dialects)
          'ء': 'ا',  # Hamza to Alif (informally)
          'ث': 'ت',
        }
    # Latin (English) specific swaps
    elif lang == 'en':
        swaps = {
          'a': 'e',  # 'a' to 'e' in informal writing
          'e': 'a',  # 'e' to 'a' in informal writing
          'o': 'u',  # 'o' to 'u' in informal writing
          'u': 'o',  # 'u' to 'o' in informal writing
          'i': 'y',  # 'i' to 'y' in informal writing
          'i': 'ee',  # 'i' to 'ee' in informal writing
          'y': 'i',  # 'y' to 'i' in informal writing
          'y': 'ee',  # 'y' to 'ee' in informal writing
          'ou': 'o',  # 'ou' to 'o' in informal writing
          'o': 'ou',  # 'o' to 'ou' in informal writing
          'ou': 'oo',  # 'ou' to 'oo' in informal writing
          'ch': 'sh',  # 'ch' to 'sh' (common for Arabic 'ش')
          's': 'z',  # 's' to 'z' (common in Egyptian Arabic and other dialects)
          'kh': 'k',  # 'kh' to 'k' (common in some dialects)
          'q': 'k',  # 'q' to 'k' (common in some dialects)
          '3': 'ع',  # '3' for 'ع' (common in Arabizi, transliteration for 'Ayn')
          '7': 'ح',  # '7' for 'ح' (common in Arabizi, transliteration for 'Haa')
          '5': 'خ',  # '5' for 'خ' (common in Arabizi, transliteration for 'Khaa')
          '6': 'ط',  # '6' for 'ط' (common in Arabizi, transliteration for 'Taa')
          '9': 'ص',  # '9' for 'ص' (common in Arabizi, transliteration for 'Sadd')
          '8': 'غ',  # '8' for 'غ' (common in Arabizi, transliteration for 'Ghayn')
          '4': 'ف',  # '4' for 'ف' (common in Arabizi, transliteration for 'Fa')
          '2': 'ا',  # '2' for 'ا' (common in Arabizi, transliteration for 'Alif')
          '0': 'و',  # '0' for 'و' (common in Arabizi, transliteration for 'Waw')
        }
    else:
        swaps = {}

    for char, swap_char in swaps.items():
        if char in word:
            new_word = word.replace(char, swap_char)
            if new_word != word:
                variations.append(new_word)

    return variations

def generate_permuted_rows(df):
    new_rows = []

    for _, row in df.iterrows():
        word = row['text']
        variations = generate_variations(word)

        for variation in variations:
            new_row = {'text': variation, 'label': row['label']}
            new_rows.append(new_row)

    # Convert the list of new rows into a DataFrame and append to the original DataFrame
    permuted_df = pd.DataFrame(new_rows)
    return pd.concat([df, permuted_df], ignore_index=True)


text = generate_permuted_rows(text)

text

            text          label
0          مهبول  cyberbullying
1           جايح  cyberbullying
2            زبل  cyberbullying
3           خرية  cyberbullying
4     الله يلعنك  cyberbullying
...          ...            ...
7623    boukarch  cyberbullying
7624   bouukerch  cyberbullying
7625    bookerch  cyberbullying
7626    bookerch  cyberbullying
7627    boukersh  cyberbullying

[7628 rows x 2 columns]

In [29]:
the_data = pd.concat([data, text], axis = 0).reset_index(drop = True)
the_data

                                         text              label
0               قاتلك هاذاك الإنسان ال gris 😭      cyberbullying
1                Never saw his skin color lol      cyberbullying
2                          السيد لي ماشي grey      cyberbullying
3      Say dok ghi syed li 3andou 1000 3adala  not cyberbullying
4                                           😂  not cyberbullying
...                                       ...                ...
38404                                boukarch      cyberbullying
38405                               bouukerch      cyberbullying
38406                                bookerch      cyberbullying
38407                                bookerch      cyberbullying
38408                                boukersh      cyberbullying

[38409 rows x 2 columns]

In [30]:
import plotly.express as px


label_counts = the_data['label'].value_counts().reset_index()
label_counts.columns = ['Label', 'Count']


fig = px.bar(
    label_counts,
    x='Label',
    y='Count',
    color='Label',
    title='Distribution of Labels',
    labels={'Category': 'Category', 'Count': 'Count'},
)

fig.update_layout(
    xaxis_title='Category',
    yaxis_title='Count',
    xaxis_tickangle=45,
    font=dict(size=12)
)


fig.show()

In [31]:
the_data = the_data.sample(frac=1, random_state=42).reset_index(drop=True)
the_data

                                                    text              label
0                                            who are you  not cyberbullying
1                                Just to make it serious  not cyberbullying
2                                            ياخي طالوسة      cyberbullying
3               nta adc w ana sup <@1138103281038667826>  not cyberbullying
4                                            اعطيني بوسه      cyberbullying
...                                                  ...                ...
38404  المهم البنات ادو معاكم بنتورة علاجال دوك الحيوط 🤡  not cyberbullying
38405                                        Na3na3tek ?      cyberbullying
38406                                    dayer ki difda3      cyberbullying
38407  Since deadline te3 registration hata le 20 so ...  not cyberbullying
38408                                          Dzai dzai  not cyberbullying

[38409 rows x 2 columns]

### Replacing tags by people's names

In [33]:
import re
import random

arabic_names = [
    'merouane', 'محمد', 'علي', 'فاطمة', 'nihel', 'خالد', 'سارة', 'مريم', 'يوسف', 'أمل',
    'عمر', 'mely', 'جميلة', 'nadine', 'فهد', 'محمود', 'نورا', 'دانية', 'سامي', 'souha'
]

def replace_mentions_with_names(text, name_list):

    mention_pattern = r'<@(\d+)>'

    def replace_with_random_name(match):
        return random.choice(name_list)

    return re.sub(mention_pattern, replace_with_random_name, text)

the_data['text'] = the_data['text'].apply(lambda x: replace_mentions_with_names(x, arabic_names))

the_data

                                                    text              label
0                                            who are you  not cyberbullying
1                                Just to make it serious  not cyberbullying
2                                            ياخي طالوسة      cyberbullying
3                                 nta adc w ana sup مريم  not cyberbullying
4                                            اعطيني بوسه      cyberbullying
...                                                  ...                ...
38404  المهم البنات ادو معاكم بنتورة علاجال دوك الحيوط 🤡  not cyberbullying
38405                                        Na3na3tek ?      cyberbullying
38406                                    dayer ki difda3      cyberbullying
38407  Since deadline te3 registration hata le 20 so ...  not cyberbullying
38408                                          Dzai dzai  not cyberbullying

[38409 rows x 2 columns]

In [34]:
the_data.to_csv('/content/drive/MyDrive/NLP project/Data/data_for_1st_ver_fine_tune.csv')